version: "3.8"

services:
  edunigo-wireframe:
    build: .
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
    stdin_open: true
    tty: true
